version: '2'
services:
  rmq:
    image: rabbitmq:3-management
    ports:
      - '8080:15672'
      - '5672:5672'
      - '5671:5671'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
#  redis:
#    image: redis:alpine
  saifudb:
    build: ./saifudb
    image: saifu/saifudb
    environment:
      POSTGRES_DB: saifudb
      POSTGRES_USER: saifudb
      POSTGRES_PASSWORD: saifudb
  mktpub:
    build: ./mktpub
    image: saifu/mktpub
    environment:
      MKTPUB_ENV: dev
      MKTPUB_PROCS: 6
    depends_on:
      - rmq
  mktagg:
    build: ./mktagg
    image: saifu/mktagg
    environment:
      MKTAGG_ENV: dev
    depends_on:
      - rmq
  ingesticks:
    build: ./ingesticks
    image: saifu/ingesticks
    environment:
      INGESTICKS_ENV: dev
    depends_on:
      - rmq
      - saifudb
  schedprice:
    build: ./schedprice
    image: saifu/schedprice
    environment:
      SCHEDPRICE_ENV: dev
    depends_on:
      - rmq
      - saifudb
  portprice:
    build: ./portprice
    image: saifu/portprice
    environment:
      PORTPRICE_ENV: dev
      PORTPRICE_PROCS: 1
    depends_on:
      - rmq
